"""Seed data for the Emtelco MVP demo.

Prices are expressed in Colombian pesos (COP). All names, identifiers and
emails are fictitious; no real personal data is used.

Edge cases intentionally included:

* products with ``stock == 0`` (iPhone 16, TCL 50" P745, AirPods Pro 2)
* one inactive product (Razer BlackShark V2)
* laptops priced just below and above the 5,000,000 budget used in Scenario 1
* warranties that are active and expired (Scenario 3)
* orders covering all six statuses
"""

DEMO_PASSWORD = "Demo1234*"

# ---------------------------------------------------------------------------
# Products (35)
# ---------------------------------------------------------------------------
PRODUCTS = [
    # --- Laptops (10) -----------------------------------------------------
    {
        "sku": "LAP-ACER-A315",
        "name": 'Acer Aspire 3 A315',
        "brand": "Acer",
        "category": "laptop",
        "description": "Portátil de entrada para estudio y ofimática.",
        "price": "2199900.00",
        "stock": 15,
        "warranty_months": 12,
        "shipping_days": 3,
        "active": True,
        "specifications": {
            "procesador": "Intel Core i3-1215U",
            "ram_gb": 8,
            "almacenamiento": "256 GB SSD",
            "gpu": "Intel UHD Graphics",
            "pantalla": '15.6" FHD',
            "peso_kg": 1.78,
            "so": "Windows 11 Home",
        },
    },
    {
        "sku": "LAP-HP-VICTUS15",
        "name": "HP Victus 15",
        "brand": "HP",
        "category": "laptop",
        "description": "Portátil gaming con GPU dedicada, apto para diseño y edición.",
        "price": "4299900.00",
        "stock": 8,
        "warranty_months": 12,
        "shipping_days": 3,
        "active": True,
        "specifications": {
            "procesador": "AMD Ryzen 5 7535HS",
            "ram_gb": 16,
            "almacenamiento": "512 GB SSD",
            "gpu": "NVIDIA GeForce RTX 2050 4GB",
            "pantalla": '15.6" FHD 144Hz',
            "peso_kg": 2.3,
            "so": "Windows 11 Home",
        },
    },
    {
        "sku": "LAP-MSI-THIN15",
        "name": "MSI Thin 15 B12UC",
        "brand": "MSI",
        "category": "laptop",
        "description": "Portátil delgado con GPU dedicada para creación de contenido.",
        "price": "4699900.00",
        "stock": 6,
        "warranty_months": 12,
        "shipping_days": 3,
        "active": True,
        "specifications": {
            "procesador": "Intel Core i5-12450H",
            "ram_gb": 16,
            "almacenamiento": "512 GB SSD",
            "gpu": "NVIDIA GeForce RTX 3050 4GB",
            "pantalla": '15.6" FHD 144Hz',
            "peso_kg": 1.86,
            "so": "Windows 11 Home",
        },
    },
    {
        "sku": "LAP-LENOVO-LOQ15",
        "name": "Lenovo LOQ 15IRH8",
        "brand": "Lenovo",
        "category": "laptop",
        "description": "Portátil gaming con RTX 3050 de 6GB, ideal para diseño gráfico.",
        "price": "4799900.00",
        "stock": 5,
        "warranty_months": 12,
        "shipping_days": 3,
        "active": True,
        "specifications": {
            "procesador": "Intel Core i5-13420H",
            "ram_gb": 16,
            "almacenamiento": "512 GB SSD",
            "gpu": "NVIDIA GeForce RTX 3050 6GB",
            "pantalla": '15.6" FHD 144Hz',
            "peso_kg": 2.38,
            "so": "Windows 11 Home",
        },
    },
    {
        "sku": "LAP-ASUS-TUFA15",
        "name": "ASUS TUF Gaming A15",
        "brand": "ASUS",
        "category": "laptop",
        "description": "Portátil robusto con Ryzen 7 y RTX 3050, buen equilibrio precio/rendimiento.",
        "price": "4999900.00",
        "stock": 4,
        "warranty_months": 12,
        "shipping_days": 3,
        "active": True,
        "specifications": {
            "procesador": "AMD Ryzen 7 7435HS",
            "ram_gb": 16,
            "almacenamiento": "512 GB SSD",
            "gpu": "NVIDIA GeForce RTX 3050 4GB",
            "pantalla": '15.6" FHD 144Hz',
            "peso_kg": 2.3,
            "so": "Windows 11 Home",
        },
    },
    {
        "sku": "LAP-DELL-INS3530",
        "name": "Dell Inspiron 15 3530",
        "brand": "Dell",
        "category": "laptop",
        "description": "Portátil de productividad con procesador de última generación.",
        "price": "3499900.00",
        "stock": 10,
        "warranty_months": 12,
        "shipping_days": 3,
        "active": True,
        "specifications": {
            "procesador": "Intel Core i7-1355U",
            "ram_gb": 16,
            "almacenamiento": "512 GB SSD",
            "gpu": "Intel Iris Xe Graphics",
            "pantalla": '15.6" FHD',
            "peso_kg": 1.62,
            "so": "Windows 11 Home",
        },
    },
    {
        "sku": "LAP-LENOVO-IPSLIM3",
        "name": "Lenovo IdeaPad Slim 3 15IRH8",
        "brand": "Lenovo",
        "category": "laptop",
        "description": "Portátil ligero para trabajo y estudio.",
        "price": "2899900.00",
        "stock": 12,
        "warranty_months": 12,
        "shipping_days": 3,
        "active": True,
        "specifications": {
            "procesador": "Intel Core i5-13420H",
            "ram_gb": 16,
            "almacenamiento": "512 GB SSD",
            "gpu": "Intel UHD Graphics",
            "pantalla": '15.6" FHD',
            "peso_kg": 1.62,
            "so": "Windows 11 Home",
        },
    },
    {
        "sku": "LAP-ASUS-VIVO16",
        "name": "ASUS Vivobook 16 M1605",
        "brand": "ASUS",
        "category": "laptop",
        "description": "Portátil de pantalla amplia para multitarea.",
        "price": "3299900.00",
        "stock": 9,
        "warranty_months": 12,
        "shipping_days": 3,
        "active": True,
        "specifications": {
            "procesador": "AMD Ryzen 5 7530U",
            "ram_gb": 16,
            "almacenamiento": "512 GB SSD",
            "gpu": "AMD Radeon Graphics",
            "pantalla": '16" WUXGA',
            "peso_kg": 1.88,
            "so": "Windows 11 Home",
        },
    },
    {
        "sku": "LAP-APPLE-MBA-M2",
        "name": 'Apple MacBook Air M2 13"',
        "brand": "Apple",
        "category": "laptop",
        "description": "Ultrabook con chip M2, excelente autonomía y pantalla Retina.",
        "price": "5499900.00",
        "stock": 7,
        "warranty_months": 12,
        "shipping_days": 2,
        "active": True,
        "specifications": {
            "procesador": "Apple M2",
            "ram_gb": 8,
            "almacenamiento": "256 GB SSD",
            "gpu": "GPU Apple 8 núcleos",
            "pantalla": '13.6" Liquid Retina',
            "peso_kg": 1.24,
            "so": "macOS",
        },
    },
    {
        "sku": "LAP-APPLE-MBP14-M3",
        "name": "Apple MacBook Pro 14 M3 Pro",
        "brand": "Apple",
        "category": "laptop",
        "description": "Portátil profesional para edición y diseño de alto rendimiento.",
        "price": "9999900.00",
        "stock": 3,
        "warranty_months": 12,
        "shipping_days": 2,
        "active": True,
        "specifications": {
            "procesador": "Apple M3 Pro",
            "ram_gb": 18,
            "almacenamiento": "512 GB SSD",
            "gpu": "GPU Apple 14 núcleos",
            "pantalla": '14.2" Liquid Retina XDR',
            "peso_kg": 1.55,
            "so": "macOS",
        },
    },
    # --- Phones (8) -------------------------------------------------------
    {
        "sku": "PHN-HONOR-X8B",
        "name": "Honor X8b",
        "brand": "Honor",
        "category": "phone",
        "description": "Celular de gama media con cámara de 108 MP.",
        "price": "999900.00",
        "stock": 20,
        "warranty_months": 12,
        "shipping_days": 2,
        "active": True,
        "specifications": {
            "pantalla": '6.7" AMOLED',
            "ram_gb": 8,
            "almacenamiento": "256 GB",
            "camara_mp": 108,
            "bateria_mah": 4500,
            "red": "4G",
            "so": "Android 13",
        },
    },
    {
        "sku": "PHN-XIAOMI-RN13P",
        "name": "Xiaomi Redmi Note 13 Pro",
        "brand": "Xiaomi",
        "category": "phone",
        "description": "Celular equilibrado con pantalla AMOLED de 120Hz.",
        "price": "1299900.00",
        "stock": 18,
        "warranty_months": 12,
        "shipping_days": 2,
        "active": True,
        "specifications": {
            "pantalla": '6.67" AMOLED 120Hz',
            "ram_gb": 8,
            "almacenamiento": "256 GB",
            "camara_mp": 200,
            "bateria_mah": 5100,
            "red": "4G",
            "so": "Android 13",
        },
    },
    {
        "sku": "PHN-SAMSUNG-A55",
        "name": "Samsung Galaxy A55 5G",
        "brand": "Samsung",
        "category": "phone",
        "description": "Gama media premium con conectividad 5G.",
        "price": "1699900.00",
        "stock": 14,
        "warranty_months": 12,
        "shipping_days": 2,
        "active": True,
        "specifications": {
            "pantalla": '6.6" Super AMOLED 120Hz',
            "ram_gb": 8,
            "almacenamiento": "128 GB",
            "camara_mp": 50,
            "bateria_mah": 5000,
            "red": "5G",
            "so": "Android 14",
        },
    },
    {
        "sku": "PHN-MOTOROLA-EDGE50",
        "name": "Motorola Edge 50",
        "brand": "Motorola",
        "category": "phone",
        "description": "Celular con pantalla pOLED de 144Hz y carga rápida.",
        "price": "2199900.00",
        "stock": 11,
        "warranty_months": 12,
        "shipping_days": 2,
        "active": True,
        "specifications": {
            "pantalla": '6.7" pOLED 144Hz',
            "ram_gb": 12,
            "almacenamiento": "256 GB",
            "camara_mp": 50,
            "bateria_mah": 5000,
            "red": "5G",
            "so": "Android 14",
        },
    },
    {
        "sku": "PHN-XIAOMI-14",
        "name": "Xiaomi 14",
        "brand": "Xiaomi",
        "category": "phone",
        "description": "Gama alta compacta con cámara Leica.",
        "price": "3599900.00",
        "stock": 6,
        "warranty_months": 12,
        "shipping_days": 2,
        "active": True,
        "specifications": {
            "pantalla": '6.36" AMOLED 120Hz',
            "ram_gb": 12,
            "almacenamiento": "256 GB",
            "camara_mp": 50,
            "bateria_mah": 4610,
            "red": "5G",
            "so": "Android 14",
        },
    },
    {
        "sku": "PHN-SAMSUNG-S24",
        "name": "Samsung Galaxy S24",
        "brand": "Samsung",
        "category": "phone",
        "description": "Gama alta con funciones de IA y pantalla Dynamic AMOLED.",
        "price": "3799900.00",
        "stock": 8,
        "warranty_months": 12,
        "shipping_days": 2,
        "active": True,
        "specifications": {
            "pantalla": '6.2" Dynamic AMOLED 120Hz',
            "ram_gb": 8,
            "almacenamiento": "256 GB",
            "camara_mp": 50,
            "bateria_mah": 4000,
            "red": "5G",
            "so": "Android 14",
        },
    },
    {
        "sku": "PHN-APPLE-IP15",
        "name": "Apple iPhone 15 128GB",
        "brand": "Apple",
        "category": "phone",
        "description": "iPhone con Dynamic Island y conector USB-C.",
        "price": "4299900.00",
        "stock": 5,
        "warranty_months": 12,
        "shipping_days": 2,
        "active": True,
        "specifications": {
            "pantalla": '6.1" Super Retina XDR',
            "ram_gb": 6,
            "almacenamiento": "128 GB",
            "camara_mp": 48,
            "bateria_mah": 3349,
            "red": "5G",
            "so": "iOS 17",
        },
    },
    {
        "sku": "PHN-APPLE-IP16",
        "name": "Apple iPhone 16 128GB",
        "brand": "Apple",
        "category": "phone",
        "description": "Última generación con Apple Intelligence.",
        "price": "5199900.00",
        "stock": 0,  # edge case: sin disponibilidad
        "warranty_months": 12,
        "shipping_days": 2,
        "active": True,
        "specifications": {
            "pantalla": '6.1" Super Retina XDR',
            "ram_gb": 8,
            "almacenamiento": "128 GB",
            "camara_mp": 48,
            "bateria_mah": 3561,
            "red": "5G",
            "so": "iOS 18",
        },
    },
    # --- TVs (7) ----------------------------------------------------------
    {
        "sku": "TV-XIAOMI-A2-43",
        "name": 'Xiaomi TV A2 43"',
        "brand": "Xiaomi",
        "category": "tv",
        "description": "Televisor inteligente Full HD para espacios pequeños.",
        "price": "1199900.00",
        "stock": 16,
        "warranty_months": 12,
        "shipping_days": 4,
        "active": True,
        "specifications": {
            "pantalla_pulgadas": 43,
            "resolucion": "Full HD",
            "panel": "LED",
            "hz": 60,
            "smart_tv": "Google TV",
            "hdmi": 3,
        },
    },
    {
        "sku": "TV-TCL-P745-50",
        "name": 'TCL 50" P745 4K',
        "brand": "TCL",
        "category": "tv",
        "description": "Televisor 4K con Google TV.",
        "price": "1799900.00",
        "stock": 0,  # edge case: sin disponibilidad
        "warranty_months": 12,
        "shipping_days": 4,
        "active": True,
        "specifications": {
            "pantalla_pulgadas": 50,
            "resolucion": "4K UHD",
            "panel": "LED",
            "hz": 60,
            "smart_tv": "Google TV",
            "hdmi": 3,
        },
    },
    {
        "sku": "TV-SAMSUNG-DU7000-55",
        "name": 'Samsung 55" Crystal UHD DU7000',
        "brand": "Samsung",
        "category": "tv",
        "description": "Televisor 4K con sistema Tizen y amplia disponibilidad.",
        "price": "2399900.00",
        "stock": 12,
        "warranty_months": 12,
        "shipping_days": 4,
        "active": True,
        "specifications": {
            "pantalla_pulgadas": 55,
            "resolucion": "4K UHD",
            "panel": "LED",
            "hz": 60,
            "smart_tv": "Tizen",
            "hdmi": 3,
        },
    },
    {
        "sku": "TV-LG-UR78-65",
        "name": 'LG 65" UHD UR78',
        "brand": "LG",
        "category": "tv",
        "description": "Televisor 4K de gran formato con webOS.",
        "price": "3199900.00",
        "stock": 7,
        "warranty_months": 12,
        "shipping_days": 4,
        "active": True,
        "specifications": {
            "pantalla_pulgadas": 65,
            "resolucion": "4K UHD",
            "panel": "LED",
            "hz": 60,
            "smart_tv": "webOS",
            "hdmi": 3,
        },
    },
    {
        "sku": "TV-SONY-X75K-55",
        "name": 'Sony Bravia 55" X75K',
        "brand": "Sony",
        "category": "tv",
        "description": "Televisor 4K con procesador de imagen X1.",
        "price": "3499900.00",
        "stock": 5,
        "warranty_months": 12,
        "shipping_days": 4,
        "active": True,
        "specifications": {
            "pantalla_pulgadas": 55,
            "resolucion": "4K UHD",
            "panel": "LED",
            "hz": 60,
            "smart_tv": "Google TV",
            "hdmi": 4,
        },
    },
    {
        "sku": "TV-SAMSUNG-Q60D-65",
        "name": 'Samsung 65" QLED Q60D',
        "brand": "Samsung",
        "category": "tv",
        "description": "Televisor QLED 4K con mayor brillo y color.",
        "price": "4499900.00",
        "stock": 4,
        "warranty_months": 12,
        "shipping_days": 4,
        "active": True,
        "specifications": {
            "pantalla_pulgadas": 65,
            "resolucion": "4K UHD",
            "panel": "QLED",
            "hz": 60,
            "smart_tv": "Tizen",
            "hdmi": 3,
        },
    },
    {
        "sku": "TV-LG-C4-55",
        "name": 'LG OLED 55" C4',
        "brand": "LG",
        "category": "tv",
        "description": "Televisor OLED 4K de 120Hz para cine y gaming.",
        "price": "6999900.00",
        "stock": 3,
        "warranty_months": 12,
        "shipping_days": 4,
        "active": True,
        "specifications": {
            "pantalla_pulgadas": 55,
            "resolucion": "4K UHD",
            "panel": "OLED",
            "hz": 120,
            "smart_tv": "webOS",
            "hdmi": 4,
        },
    },
    # --- Accessories (10) -------------------------------------------------
    {
        "sku": "ACC-ANKER-PB20K",
        "name": "Anker PowerCore 20000",
        "brand": "Anker",
        "category": "accessory",
        "description": "Batería portátil de 20.000 mAh con carga rápida.",
        "price": "199900.00",
        "stock": 30,
        "warranty_months": 6,
        "shipping_days": 2,
        "active": True,
        "specifications": {
            "tipo": "Power bank",
            "capacidad_mah": 20000,
            "salida_w": 22.5,
            "puertos": 2,
        },
    },
    {
        "sku": "ACC-LOGITECH-C920",
        "name": "Logitech C920 HD Pro",
        "brand": "Logitech",
        "category": "accessory",
        "description": "Webcam Full HD con micrófono integrado.",
        "price": "349900.00",
        "stock": 22,
        "warranty_months": 12,
        "shipping_days": 2,
        "active": True,
        "specifications": {
            "tipo": "Webcam",
            "resolucion": "1080p",
            "fps": 30,
            "microfono": "integrado",
        },
    },
    {
        "sku": "ACC-LOGITECH-MXM3S",
        "name": "Logitech MX Master 3S",
        "brand": "Logitech",
        "category": "accessory",
        "description": "Mouse inalámbrico ergonómico de alta precisión.",
        "price": "399900.00",
        "stock": 18,
        "warranty_months": 12,
        "shipping_days": 2,
        "active": True,
        "specifications": {
            "tipo": "Mouse",
            "conexion": "Bluetooth / USB",
            "dpi": 8000,
            "botones": 7,
        },
    },
    {
        "sku": "ACC-JBL-T770NC",
        "name": "JBL Tune 770NC",
        "brand": "JBL",
        "category": "accessory",
        "description": "Audífonos con cancelación activa de ruido.",
        "price": "449900.00",
        "stock": 25,
        "warranty_months": 12,
        "shipping_days": 2,
        "active": True,
        "specifications": {
            "tipo": "Audífonos",
            "cancelacion_ruido": "Sí",
            "bateria_h": 70,
            "conexion": "Bluetooth 5.3",
        },
    },
    {
        "sku": "ACC-RAZER-BHV2",
        "name": "Razer BlackShark V2",
        "brand": "Razer",
        "category": "accessory",
        "description": "Audífonos gamer THX Spatial (descontinuado).",
        "price": "549900.00",
        "stock": 0,
        "warranty_months": 12,
        "shipping_days": 2,
        "active": False,  # edge case: producto inactivo
        "specifications": {
            "tipo": "Audífonos gamer",
            "conexion": "USB / 3.5mm",
            "microfono": "desmontable",
            "sonido": "THX Spatial",
        },
    },
    {
        "sku": "ACC-LOGITECH-GPXS2",
        "name": "Logitech G Pro X Superlight 2",
        "brand": "Logitech",
        "category": "accessory",
        "description": "Mouse gamer inalámbrico ultraligero.",
        "price": "699900.00",
        "stock": 7,
        "warranty_months": 12,
        "shipping_days": 2,
        "active": True,
        "specifications": {
            "tipo": "Mouse gamer",
            "conexion": "Inalámbrica",
            "dpi": 32000,
            "peso_g": 60,
        },
    },
    {
        "sku": "ACC-TPLINK-DECOX50",
        "name": "TP-Link Deco X50 (3 unidades)",
        "brand": "TP-Link",
        "category": "accessory",
        "description": "Sistema WiFi mesh para cobertura de toda la casa.",
        "price": "699900.00",
        "stock": 10,
        "warranty_months": 24,
        "shipping_days": 3,
        "active": True,
        "specifications": {
            "tipo": "Router mesh",
            "cobertura_m2": 350,
            "wifi": "Wi-Fi 6",
            "puertos": 3,
        },
    },
    {
        "sku": "ACC-SAMSUNG-GW6",
        "name": "Samsung Galaxy Watch 6",
        "brand": "Samsung",
        "category": "accessory",
        "description": "Reloj inteligente con monitor de salud.",
        "price": "1099900.00",
        "stock": 9,
        "warranty_months": 12,
        "shipping_days": 2,
        "active": True,
        "specifications": {
            "tipo": "Smartwatch",
            "pantalla": '1.3" AMOLED',
            "bateria_h": 40,
            "conexion": "Bluetooth / Wi-Fi",
        },
    },
    {
        "sku": "ACC-APPLE-APP2",
        "name": "Apple AirPods Pro 2",
        "brand": "Apple",
        "category": "accessory",
        "description": "Audífonos inalámbricos con cancelación de ruido.",
        "price": "1199900.00",
        "stock": 0,  # edge case: sin disponibilidad
        "warranty_months": 12,
        "shipping_days": 2,
        "active": True,
        "specifications": {
            "tipo": "Audífonos",
            "cancelacion_ruido": "Sí",
            "bateria_h": 6,
            "conexion": "Bluetooth",
        },
    },
    {
        "sku": "ACC-LG-27ULTRAGEAR",
        "name": 'LG UltraGear 27" 1440p 165Hz',
        "brand": "LG",
        "category": "accessory",
        "description": "Monitor IPS 1440p de 165Hz ideal para diseño y gaming.",
        "price": "1299900.00",
        "stock": 6,
        "warranty_months": 36,
        "shipping_days": 4,
        "active": True,
        "specifications": {
            "tipo": "Monitor",
            "pulgadas": 27,
            "resolucion": "1440p",
            "hz": 165,
            "panel": "IPS",
        },
    },
]

# ---------------------------------------------------------------------------
# Customers (3) — fictitious data only
# ---------------------------------------------------------------------------
CUSTOMERS = [
    {
        "identification": "1023456789",
        "full_name": "Andrés Felipe Ríos",
        "phone": "3101234567",
        "email": "andres.rios@example.com",
        "with_user": True,  # primary demo account
    },
    {
        "identification": "1098765432",
        "full_name": "María José Ñáñez",
        "phone": "6012345678",
        "email": "maria.nanez@example.com",
        "with_user": True,  # used for isolation checks
    },
    {
        "identification": "1122334455",
        "full_name": "Carlos Andrés Pérez",
        "phone": "3159876543",
        "email": "carlos.perez@example.com",
        # no user: can be claimed by registering with this identification
        "with_user": False,
    },
]

# ---------------------------------------------------------------------------
# Orders + warranties
#
# ``key`` is a stable identifier used to make seeding idempotent.
# ``days_from_now`` is relative to today for estimated delivery dates.
# ``warranty`` holds coverage info when the order carries a warranty.
# ---------------------------------------------------------------------------
ADDRESS_A = "Cra 45 # 12-34, Apto 501, Bogotá"
ADDRESS_B = "Calle 80 # 23-10, Medellín"
ADDRESS_C = "Av. 6N # 15-20, Cali"

ORDERS = [
    {
        "key": "A-TV-DU7000",
        "customer": "1023456789",
        "sku": "TV-SAMSUNG-DU7000-55",
        "quantity": 1,
        "status": "out_for_delivery",
        "tracking_number": "EMT-2026-000123",
        "shipping_address": ADDRESS_A,
        "days_from_now": 0,  # llega hoy -> Escenario 2 y 3
        "warranty": {
            "coverage_status": "active",
            "expiration_days_from_now": 240,
            "conditions": "Cubre defectos de fábrica en panel y electrónica. No cubre daños físicos ni humedad.",
        },
    },
    {
        "key": "A-LAP-TUFA15",
        "customer": "1023456789",
        "sku": "LAP-ASUS-TUFA15",
        "quantity": 1,
        "status": "delivered",
        "tracking_number": "EMT-2026-000098",
        "shipping_address": ADDRESS_A,
        "days_from_now": -20,
        "warranty": {
            "coverage_status": "active",
            "expiration_days_from_now": 120,
            "conditions": "Garantía de fábrica por defectos de hardware.",
        },
    },
    {
        "key": "A-PHN-IP15",
        "customer": "1023456789",
        "sku": "PHN-APPLE-IP15",
        "quantity": 1,
        "status": "processing",
        "tracking_number": "",
        "shipping_address": ADDRESS_A,
        "days_from_now": 3,
        "warranty": None,
    },
    {
        "key": "A-ACC-JBL",
        "customer": "1023456789",
        "sku": "ACC-JBL-T770NC",
        "quantity": 2,
        "status": "delayed",
        "tracking_number": "EMT-2026-000201",
        "shipping_address": ADDRESS_A,
        "days_from_now": -2,  # retrasado
        "warranty": None,
    },
    {
        "key": "A-ACC-LG27",
        "customer": "1023456789",
        "sku": "ACC-LG-27ULTRAGEAR",
        "quantity": 1,
        "status": "cancelled",
        "tracking_number": "",
        "shipping_address": ADDRESS_A,
        "days_from_now": None,
        "warranty": None,
    },
    {
        "key": "A-TV-SONY",
        "customer": "1023456789",
        "sku": "TV-SONY-X75K-55",
        "quantity": 1,
        "status": "delivered",
        "tracking_number": "EMT-2024-000010",
        "shipping_address": ADDRESS_A,
        "days_from_now": -400,
        "warranty": {
            "coverage_status": "expired",
            "expiration_days_from_now": -380,  # garantía vencida
            "conditions": "Cobertura finalizada. Aplica soporte técnico con costo.",
        },
    },
    {
        "key": "A-ACC-ANKER",
        "customer": "1023456789",
        "sku": "ACC-ANKER-PB20K",
        "quantity": 1,
        "status": "shipped",
        "tracking_number": "EMT-2026-000210",
        "shipping_address": ADDRESS_A,
        "days_from_now": 1,
        "warranty": None,
    },
    {
        "key": "B-PHN-S24",
        "customer": "1098765432",
        "sku": "PHN-SAMSUNG-S24",
        "quantity": 1,
        "status": "shipped",
        "tracking_number": "EMT-2026-000155",
        "shipping_address": ADDRESS_B,
        "days_from_now": 2,
        "warranty": {
            "coverage_status": "expired",
            "expiration_days_from_now": -30,
            "conditions": "Garantía vencida.",
        },
    },
    {
        "key": "B-LAP-HP",
        "customer": "1098765432",
        "sku": "LAP-HP-VICTUS15",
        "quantity": 1,
        "status": "delivered",
        "tracking_number": "EMT-2026-000140",
        "shipping_address": ADDRESS_B,
        "days_from_now": -8,
        "warranty": {
            "coverage_status": "active",
            "expiration_days_from_now": 300,
            "conditions": "Garantía de fábrica por defectos de hardware.",
        },
    },
    {
        "key": "C-TV-LG65",
        "customer": "1122334455",
        "sku": "TV-LG-UR78-65",
        "quantity": 1,
        "status": "delivered",
        "tracking_number": "EMT-2026-000177",
        "shipping_address": ADDRESS_C,
        "days_from_now": -5,
        "warranty": {
            "coverage_status": "active",
            "expiration_days_from_now": 200,
            "conditions": "Garantía de fábrica en panel y electrónica.",
        },
    },
]
